CREATE TYPE revision_history_status AS ENUM ('update', 'delete', 'create');

CREATE TABLE revision_history (
    revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    object_id BIGINT NOT NULL,
    object_type VARCHAR(128) NOT NULL,
    modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user" VARCHAR(128) NOT NULL DEFAULT '',
    object TEXT,
    status revision_history_status NOT NULL DEFAULT 'update',
    PRIMARY KEY (revision_id, modified)
);

CREATE INDEX idx_revision_history_object_modified ON revision_history (object_type, object_id, modified);
CREATE INDEX idx_revision_history_modified_type ON revision_history (object_type, modified);

-- PostgreSQL supports table partitioning; configure RANGE partitioning on modified if needed.
